# Generated by Django 2.2 on 2020-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='moviePoster',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
